name: Build

on:
  push:
    branches: [ localstack ]
    tags: v*.*
  pull_request:
    branches: [ localstack ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'
        
    - name: Build
      env:
        RELEASE_BUILD_LINKER_FLAGS: "-s -w"
      run: make compile-lambda-linux-all
      
    - uses: actions/upload-artifact@v4
      with:
        name: aws-lambda-rie
        path: bin/*
    - name: Release binaries
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: bin/*
        generate_release_notes: true
        prerelease: ${{ endsWith(github.ref, '-pre') }}
